<?php
/**
 * Created by PhpStorm.
 * User: A
 * Date: 2016/9/16
 * Time: 23:52
 */
namespace components;

use yii\base\Widget;
use yii\helpers\Html;
use yii;
use backend\models\Faq;
use backend\models\search\FaqSearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\Pagination;

class FaqWidget extends Widget
{

    public $models;
    public $pages;
    public $settings = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if(!isset($this->settings['pageSize'])){
            $this->settings['pageSize'] = 2;
        }

        if($this->settings['featuredOnly'] === true){
            $query = Faq::find()->where(['faq_is_featured' => 1]);
        }else{
            $query = Faq::find();
        }

        $query->orderBy(['faq_weight'=>SORT_ASC]);
        $countQuery = clone $query;
        $this->pages = new Pagination([
            'defaultPageSize'=>$this->settings['pageSize'],
            'totalCount'=>$countQuery->count()
        ]);

        $this->models = $query->offset($this->pages->offset)->limit($this->pages->limit)->all();
    }


    public function run()
    {
        return $this->render('faq',[
            'models'=>$this->models,
            'pages'=>$this->pages,
            'settings'=>$this->settings
        ]);
    }

}